version: '3'
services:
  app:
    build: .
    container_name: newjhead_app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/newjhead
      REDIS_HOST: redis
      PORT: 3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
